steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['get', 'nodes']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=europe-west3'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'
  - 'no_proxy=google.internal,googleapis.com'
  - 'https_proxy=proxy.example.internal:3128'
options:
  workerPool:
    'projects/entur-project/locations/europe-west3/workerPools/mypool'
